/**
 * Dexie schema for Lyre's local-first data layer (task A3).
 *
 * Tables mirror SongRecord / ChartRecord / PatternRecord from
 * `src/lib/theory/types.ts` (docs/domain-model.md §5):
 *
 *   Song 1──* Chart 1──* Pattern (one flagged preferred)
 *
 * IDs are `crypto.randomUUID()`, generated by the repository layer — Dexie
 * primary keys here are plain (non-auto-increment) `id` strings.
 */

import Dexie, { type EntityTable } from 'dexie';
import type { SongRecord, ChartRecord, PatternRecord } from '$lib/theory/types';

export class LyreDatabase extends Dexie {
	songs!: EntityTable<SongRecord, 'id'>;
	charts!: EntityTable<ChartRecord, 'id'>;
	patterns!: EntityTable<PatternRecord, 'id'>;

	constructor(name = 'lyre') {
		super(name);

		this.version(1).stores({
			// title/updatedAt indexed for alpha + recently-added sorts;
			// lastPlayedAt (additive field, see types.ts) for recently-played.
			songs: 'id, title, updatedAt, lastPlayedAt',
			// songId indexed to list a song's charts.
			charts: 'id, songId',
			// chartId for listing a chart's patterns; compound index for the
			// exactly-one-preferred invariant (domain-model.md §5).
			patterns: 'id, chartId, [chartId+isPreferred]'
		});
	}
}

/** Shared singleton instance used by the repository layer. */
export const db = new LyreDatabase();

/** Create a fresh, independently-named database instance (tests only). */
export function createTestDatabase(name: string): LyreDatabase {
	return new LyreDatabase(name);
}
